apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
    env: dev
  name: app-service
  namespace: development
spec:
  ports:
  - name: app-svcport
    port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    app: myapp
    name: myapp
  type: NodePort
